import axios from "axios";
import Head from 'next/head'
import Image from 'next/image'

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Image src={props.header_logo_url} width={159} height={50} />
        <input value={props.header_logo_url} width="100%"/>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  const appearanceDataRaw = (
    await axios.get(`https://donation-form-staging.herokuapp.com/api/v2/drf/appearance/`)
  ).data[0];
  return {
    props: {
      header_logo_url: appearanceDataRaw.header_logo.url,
    },
  };
}
